# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/hash.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblInput = QtWidgets.QLabel(self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(30, 120, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblInput.setFont(font)
        self.lblInput.setObjectName("lblInput")
        self.txtInput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(20, 150, 281, 71))
        self.txtInput.setObjectName("txtInput")
        self.lblAlgo = QtWidgets.QLabel(self.centralwidget)
        self.lblAlgo.setGeometry(QtCore.QRect(20, 240, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblAlgo.setFont(font)
        self.lblAlgo.setObjectName("lblAlgo")
        self.cboAlgo = QtWidgets.QComboBox(self.centralwidget)
        self.cboAlgo.setGeometry(QtCore.QRect(20, 270, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cboAlgo.setFont(font)
        self.cboAlgo.setObjectName("cboAlgo")
        self.cboAlgo.addItem("")
        self.cboAlgo.addItem("")
        self.cboAlgo.addItem("")
        self.cboAlgo.addItem("")
        self.btnHash = QtWidgets.QPushButton(self.centralwidget)
        self.btnHash.setGeometry(QtCore.QRect(20, 340, 281, 41))
        self.btnHash.setObjectName("btnHash")
        self.lblOutput_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblOutput_2.setGeometry(QtCore.QRect(440, 120, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblOutput_2.setFont(font)
        self.lblOutput_2.setObjectName("lblOutput_2")
        self.txtOutput = QtWidgets.QLineEdit(self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(440, 150, 321, 111))
        self.txtOutput.setObjectName("txtOutput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Hash Cipher"))
        self.lblInput.setText(_translate("MainWindow", "Chuỗi cần băm:"))
        self.lblAlgo.setText(_translate("MainWindow", "Thuật toán:"))
        self.cboAlgo.setItemText(0, _translate("MainWindow", "MD5"))
        self.cboAlgo.setItemText(1, _translate("MainWindow", "SHA-256"))
        self.cboAlgo.setItemText(2, _translate("MainWindow", "SHA-3"))
        self.cboAlgo.setItemText(3, _translate("MainWindow", "BLAKE2"))
        self.btnHash.setText(_translate("MainWindow", "Hash"))
        self.lblOutput_2.setText(_translate("MainWindow", "Kết quả:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
