# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'websocket/ui/ws_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 0, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus.setGeometry(QtCore.QRect(360, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblStatus.setFont(font)
        self.lblStatus.setObjectName("lblStatus")
        self.txtLog = QtWidgets.QTextEdit(self.centralwidget)
        self.txtLog.setGeometry(QtCore.QRect(30, 210, 371, 71))
        self.txtLog.setObjectName("txtLog")
        self.txtMessage = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMessage.setGeometry(QtCore.QRect(470, 210, 301, 51))
        self.txtMessage.setObjectName("txtMessage")
        self.lblStatus_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus_2.setGeometry(QtCore.QRect(470, 170, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblStatus_2.setFont(font)
        self.lblStatus_2.setObjectName("lblStatus_2")
        self.btnSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(470, 290, 301, 31))
        self.btnSend.setObjectName("btnSend")
        self.lblStatus_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus_3.setGeometry(QtCore.QRect(30, 180, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblStatus_3.setFont(font)
        self.lblStatus_3.setObjectName("lblStatus_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Web Socket"))
        self.lblStatus.setText(_translate("MainWindow", "Đang kết nối..."))
        self.lblStatus_2.setText(_translate("MainWindow", "Nhập thông điệp"))
        self.btnSend.setText(_translate("MainWindow", "Gửi"))
        self.lblStatus_3.setText(_translate("MainWindow", "Hiển thị "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
