# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dh_key_pair/ui/dh.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gbServer = QtWidgets.QGroupBox(self.centralwidget)
        self.gbServer.setGeometry(QtCore.QRect(0, 90, 321, 471))
        self.gbServer.setObjectName("gbServer")
        self.btnGenServer = QtWidgets.QPushButton(self.gbServer)
        self.btnGenServer.setGeometry(QtCore.QRect(10, 140, 111, 41))
        self.btnGenServer.setObjectName("btnGenServer")
        self.txtServerPub = QtWidgets.QTextEdit(self.gbServer)
        self.txtServerPub.setGeometry(QtCore.QRect(10, 60, 271, 71))
        self.txtServerPub.setObjectName("txtServerPub")
        self.label_2 = QtWidgets.QLabel(self.gbServer)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtServerShared = QtWidgets.QTextEdit(self.gbServer)
        self.txtServerShared.setGeometry(QtCore.QRect(10, 240, 271, 71))
        self.txtServerShared.setObjectName("txtServerShared")
        self.label_4 = QtWidgets.QLabel(self.gbServer)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gbClient = QtWidgets.QGroupBox(self.centralwidget)
        self.gbClient.setGeometry(QtCore.QRect(440, 90, 321, 471))
        self.gbClient.setObjectName("gbClient")
        self.btnGenClient = QtWidgets.QPushButton(self.gbClient)
        self.btnGenClient.setGeometry(QtCore.QRect(10, 140, 111, 41))
        self.btnGenClient.setObjectName("btnGenClient")
        self.txtClientShared = QtWidgets.QTextEdit(self.gbClient)
        self.txtClientShared.setGeometry(QtCore.QRect(10, 60, 271, 71))
        self.txtClientShared.setObjectName("txtClientShared")
        self.label_3 = QtWidgets.QLabel(self.gbClient)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lblStatus = QtWidgets.QLabel(self.gbClient)
        self.lblStatus.setGeometry(QtCore.QRect(20, 210, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbServer.setTitle(_translate("MainWindow", "Server"))
        self.btnGenServer.setText(_translate("MainWindow", "Generate"))
        self.label_2.setText(_translate("MainWindow", "Show public key:"))
        self.label_4.setText(_translate("MainWindow", "Server shared:"))
        self.label.setText(_translate("MainWindow", " Diffie-Hellman key exchange"))
        self.gbClient.setTitle(_translate("MainWindow", "Client"))
        self.btnGenClient.setText(_translate("MainWindow", "Generate key"))
        self.label_3.setText(_translate("MainWindow", "Client shared:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
